version: 0.2

# env:
#   environment: "dev"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
    
      - cd ETL
      - npm install -g serverless@3.24.1
      - echo change location to ETL directory
      - npm install --silent
    
  build:
    commands:
      - echo deploying functions for 4chealth-etl
      - serverless deploy
      - echo finished deploying functions

     
      