AWSTemplateFormatVersion: 2010-09-09
Description: Bastion template for 4Chealth Data Warehouse

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VPCID
      - VPCSubnetID
      - SSHRemoteAccessCIDR
      - BastionKeyPairName
      - EnvironmentType
    ParameterLabels:
      VPCID:
        default: VPC ID
      VPCSubnetID:
        default: VPC Subnet
      SSHRemoteAccessCIDR:
        default: Allowed bastion external access CIDR
      BastionKeyPairName:
        default: Bastion host key pair name

Parameters:
  VPCID:
    Description: A VPC ID
    Type: String
  VPCSubnetID:
    Description: A VPC subnet ID
    Type: String
  SSHRemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the bastions
    Type: String
  BastionKeyPairName: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be a valid Key Pair
  EnvironmentType:
      Default: dev
      Description: Deployment environment 
      Type: String

Resources:
  BastionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPCID
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHRemoteAccessCIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentType}-4ChealthBastionSG-DWH

  BastionHost:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-05c42683296709b61
      InstanceType: t3.micro
      KeyName: !Ref BastionKeyPairName
      SubnetId: !Ref VPCSubnetID
      SecurityGroupIds: 
        - !Ref BastionSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentType}-4ChealthBastionHost-DWH

Outputs:
  BastionHostDNS:
    Description: Bastion host public DNS
    Value: !GetAtt BastionHost.PublicDnsName
  BastionPublicIPAddress:
    Description: Bastion host public IP
    Value: !GetAtt BastionHost.PublicIp
  BastionSG:
    Description: Bastion security group
    Value: !Ref BastionSecurityGroup