
AWSTemplateFormatVersion: 2010-09-09
Description: VPC template for 4Chealth ETL and  Data Warehouse

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Environment
      Parameters:
        - EnvironmentType
    - Label:
        default: Network Configuration
      Parameters:
      - VPCCIDR
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - PublicSubnet3CIDR
      - PrivateSubnet1CIDR
      - PrivateSubnet2CIDR
      - PrivateSubnet3CIDR
      - SSHRemoteAccessCIDR
    # - Label:
    #     default: Redshift DWH Publicly Accessible
    #   Parameters:
    #   - PubliclyAccessible
    - Label:
        default: App Instance Configuration
      Parameters:
      - ServerInstanceType
      - BastionKeyPairName
    ParameterLabels:
      VPCCIDR:
        default: VPC CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      PublicSubnet3CIDR:
        default: Public subnet 3 CIDR
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PrivateSubnet3CIDR:
        default: Private subnet 3 CIDR
      SSHRemoteAccessCIDR:
        default: Allowed bastion external access CIDR
      BastionKeyPairName:
        default: Bastion host key pair name
      # PubliclyAccessible:
      #   default: Redshift DWH public access enabled
      # ServerInstanceType:
      #   default: App node instance type
      # EnvironmentType:
      #   default: Environment Type

Parameters:
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.1.0/24
    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone 1
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.2.0/24
    Description: CIDR Block for the public DMZ subnet 2 located in Availability Zone 2
    Type: String
  PublicSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.3.0/24
    Description: CIDR Block for the public DMZ subnet 3 located in Availability Zone 3
    Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.10.0/24
    Description: CIDR block for private subnet 1 located in Availability Zone 1
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.11.0/24
    Description: CIDR block for private subnet 2 located in Availability Zone 2
    Type: String
  PrivateSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 10.0.12.0/24
    Description: CIDR block for private subnet 3 located in Availability Zone 3
    Type: String
  SSHRemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the bastions
    Type: String
  BastionKeyPairName: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be a valid Key Pair
  # PubliclyAccessible: 
  #   Type: Boolean
  #   AllowedValues: [true, false]
  # ALBAccessCIDR:
  #   Description: ALB access CIDR
  #   Type: String
  #   Default: 0.0.0.0/0
  # AgilePartnerCert:
  #   Description: Agile Partner SSL Certificate ARN
  #   Type: String
  #   ConstraintDescription: must be a valid Certificate ARN
  ServerInstanceType:
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    ConstraintDescription: Choose an instance type.
    Default: t2.micro
    Description: App node  instance type
    Type: String
  EnvironmentType: 
      Description: The environment type
      Type: String
      Default: dev
      AllowedValues: 
        - prod
        - dev
        - qa
      ConstraintDescription: must be a prod , dev or qa

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://sandclinic-dwh-etl-cf-scripts.s3.eu-north-1.amazonaws.com/vpc.yaml
      Parameters:
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3CIDR: !Ref PrivateSubnet3CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PublicSubnet3CIDR: !Ref PublicSubnet3CIDR
        VPCCIDR: !Ref VPCCIDR
        EnvironmentType : !Ref EnvironmentType
  # BastionStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://sandclinic-dwh-etl-cf-scripts.s3.eu-north-1.amazonaws.com/bastion.yaml
  #     Parameters:
  #       VPCID: !GetAtt VPCStack.Outputs.4ChealthDVPCID
  #       VPCSubnetID: !GetAtt VPCStack.Outputs.4ChealthPublic1
  #       SSHRemoteAccessCIDR: !Ref SSHRemoteAccessCIDR
  #       BastionKeyPairName: !Ref BastionKeyPairName
  #       EnvironmentType : !Ref EnvironmentType

  RedshiftDWHStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://sandclinic-dwh-etl-cf-scripts.s3.eu-north-1.amazonaws.com/redshift.yaml
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.4ChealthDVPCID
        VPCSubnetID1: !GetAtt VPCStack.Outputs.4ChealthPrivate1
        VPCSubnetID2: !GetAtt VPCStack.Outputs.4ChealthPrivate2
        VPCSubnetID3: !GetAtt VPCStack.Outputs.4ChealthPrivate3
        EnvironmentType : !Ref EnvironmentType
        # PubliclyAccessible: !Ref PubliclyAccessible

  RedshiftKMSKeyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://sandclinic-dwh-etl-cf-scripts.s3.eu-north-1.amazonaws.com/awskms.yaml
     
  RedShiftS3EndPointStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://sandclinic-dwh-etl-cf-scripts.s3.eu-north-1.amazonaws.com/s3vpcendpoint.yaml
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.4ChealthDVPCID
        VPCSubnetID1: !GetAtt VPCStack.Outputs.4ChealthPrivate1
        # VPCSubnetID2: !GetAtt VPCStack.Outputs.4ChealthPrivate2
        # VPCSubnetID3: !GetAtt VPCStack.Outputs.4ChealthPrivate3
        RouteTableId : !GetAtt VPCStack.Outputs.4CHealthPrivateRouteTable
        SecurityGroupId1 : !GetAtt RedshiftDWHStack.Outputs.RedshiftSG
        # SecurityGroupId2 : !GetAtt VPCStack.Outputs.4ChealthPrivate3

  GlueETLStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://sandclinic-dwh-etl-cf-scripts.s3.eu-north-1.amazonaws.com/awsglueetl.yaml
      Parameters:
        RedshiftSecret: !GetAtt RedshiftDWHStack.Outputs.RedshiftSecret
        RedshiftSG: !GetAtt RedshiftDWHStack.Outputs.RedshiftSG
        VPCSubnetID1: !GetAtt VPCStack.Outputs.4ChealthPrivate1
        RedshiftURL: !Sub 'jdbc:redshift://${EnvironmentType}-sandclinic-wg.846996571657.eu-west-1.redshift-serverless.amazonaws.com:5439/dev'
        

         
     
       
 